using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Mooege.Common.Helpers;
using Mooege.Net.GS.Message;

namespace Mooege.Core.Common.Items
{
    partial class AffixDefinition
    {
        public readonly static AffixDefinition[][] Definitions = new AffixDefinition[][]
        {
            new AffixDefinition[]
            {
                new AffixDefinition("CriticalD I", AffixType.Prefix, 4).AddEffect("Crit_Damage_Percent", 20f, 25f),
                new AffixDefinition("CriticalD II", AffixType.Prefix, 10).AddEffect("Crit_Damage_Percent", 26f, 30f),
                new AffixDefinition("CriticalD III", AffixType.Prefix, 16).AddEffect("Crit_Damage_Percent", 31f, 35f),
                new AffixDefinition("CriticalD IV", AffixType.Prefix, 22).AddEffect("Crit_Damage_Percent", 36f, 40f),
                new AffixDefinition("CriticalD V", AffixType.Prefix, 28).AddEffect("Crit_Damage_Percent", 41f, 45f),
                new AffixDefinition("CriticalD VI", AffixType.Prefix, 34).AddEffect("Crit_Damage_Percent", 46f, 50f),
                new AffixDefinition("CriticalD VII", AffixType.Prefix, 40).AddEffect("Crit_Damage_Percent", 51f, 55f),
                new AffixDefinition("CriticalD VIII", AffixType.Prefix, 46).AddEffect("Crit_Damage_Percent", 56f, 60f),
                new AffixDefinition("CriticalD IX", AffixType.Prefix, 52).AddEffect("Crit_Damage_Percent", 61f, 65f),
                new AffixDefinition("CriticalD X", AffixType.Prefix, 58).AddEffect("Crit_Damage_Percent", 66f, 75f),
            },
            new AffixDefinition[]
            {
                new AffixDefinition("Life I", AffixType.Prefix, 8).AddEffect("Hitpoints_Percent", 11f, 15f),
                new AffixDefinition("Life II", AffixType.Prefix, 14).AddEffect("Hitpoints_Percent", 16f, 30f),
                new AffixDefinition("Life III", AffixType.Prefix, 20).AddEffect("Hitpoints_Percent", 31f, 45f),
                new AffixDefinition("Life IV", AffixType.Prefix, 26).AddEffect("Hitpoints_Percent", 46f, 60f),
                new AffixDefinition("Life V", AffixType.Prefix, 32).AddEffect("Hitpoints_Percent", 61f, 75f),
                new AffixDefinition("Life VI", AffixType.Prefix, 38).AddEffect("Hitpoints_Percent", 76f, 90f),
                new AffixDefinition("Life VII", AffixType.Prefix, 46).AddEffect("Hitpoints_Percent", 91f, 105f),
                new AffixDefinition("Life VIII", AffixType.Prefix, 54).AddEffect("Hitpoints_Percent", 106f, 115f),
                new AffixDefinition("Life IX", AffixType.Prefix, 60).AddEffect("Hitpoints_Percent", 116f, 150f),
            },
            new AffixDefinition[]
            {
                new AffixDefinition("Gold I", AffixType.Prefix, 6).AddEffect("Gold_Find", 25f, 39f),
                new AffixDefinition("Gold II", AffixType.Prefix, 11).AddEffect("Gold_Find", 40f, 54f),
                new AffixDefinition("Gold III", AffixType.Prefix, 17).AddEffect("Gold_Find", 55f, 69f),
                new AffixDefinition("Gold IV", AffixType.Prefix, 22).AddEffect("Gold_Find", 70f, 84f),
                new AffixDefinition("Gold V", AffixType.Prefix, 28).AddEffect("Gold_Find", 85f, 99f),
                new AffixDefinition("Gold VI", AffixType.Prefix, 33).AddEffect("Gold_Find", 100f, 114f),
                new AffixDefinition("Gold VII", AffixType.Prefix, 38).AddEffect("Gold_Find", 115f, 129f),
                new AffixDefinition("Gold VIII", AffixType.Prefix, 44).AddEffect("Gold_Find", 130f, 144f),
                new AffixDefinition("Gold IX", AffixType.Prefix, 49).AddEffect("Gold_Find", 145f, 159f),
                new AffixDefinition("Gold X", AffixType.Prefix, 55).AddEffect("Gold_Find", 160f, 174f),
            },
            new AffixDefinition[]
            {
                new AffixDefinition("MF I", AffixType.Prefix, 1).AddEffect("Magic_Find", 5f, 9f),
                new AffixDefinition("MF II", AffixType.Prefix, 6).AddEffect("Magic_Find", 10f, 14f),
                new AffixDefinition("MF III", AffixType.Prefix, 11).AddEffect("Magic_Find", 15f, 19f),
                new AffixDefinition("MF IV", AffixType.Prefix, 17).AddEffect("Magic_Find", 20f, 24f),
                new AffixDefinition("MF V", AffixType.Prefix, 22).AddEffect("Magic_Find", 25f, 29f),
                new AffixDefinition("MF VI", AffixType.Prefix, 28).AddEffect("Magic_Find", 30f, 34f),
                new AffixDefinition("MF VII", AffixType.Prefix, 33).AddEffect("Magic_Find", 35f, 39f),
                new AffixDefinition("MF VIII", AffixType.Prefix, 38).AddEffect("Magic_Find", 40f, 44f),
                new AffixDefinition("MF IX", AffixType.Prefix, 44).AddEffect("Magic_Find", 45f, 49f),
                new AffixDefinition("MF X", AffixType.Prefix, 49).AddEffect("Magic_Find", 50f, 54f),
                new AffixDefinition("MF XI", AffixType.Prefix, 55).AddEffect("Magic_Find", 55f, 70f),
            },

            new AffixDefinition[]
            {
                new AffixDefinition("AttPrec I", AffixType.Prefix, 70).AddEffect("Attack", 1, 6).AddEffect("Precision", 1, 6),
                new AffixDefinition("AttPrec II", AffixType.Prefix, 70).AddEffect("Attack", 6, 16).AddEffect("Precision", 6, 16),
                new AffixDefinition("AttPrec III", AffixType.Prefix, 16).AddEffect("Attack", 10, 28).AddEffect("Precision", 10, 28),
                new AffixDefinition("AttPrec IV", AffixType.Prefix, 24).AddEffect("Attack", 15, 39).AddEffect("Precision", 15, 39),
                new AffixDefinition("AttPrec V", AffixType.Prefix, 32).AddEffect("Attack", 18, 50).AddEffect("Precision", 18, 50),
                new AffixDefinition("AttPrec VI", AffixType.Prefix, 38).AddEffect("Attack", 22, 59).AddEffect("Precision", 22, 59),
                new AffixDefinition("AttPrec VII", AffixType.Prefix, 44).AddEffect("Attack", 25, 67).AddEffect("Precision", 25, 67),
                new AffixDefinition("AttPrec VIII", AffixType.Prefix, 50).AddEffect("Attack", 28, 74).AddEffect("Precision", 28, 74),
                new AffixDefinition("AttPrec IX", AffixType.Prefix, 53).AddEffect("Attack", 29, 78).AddEffect("Precision", 29, 78),
                new AffixDefinition("AttPrec X", AffixType.Prefix, 56).AddEffect("Attack", 31, 83).AddEffect("Precision", 31, 83),
                new AffixDefinition("AttPrec XI", AffixType.Prefix, 59).AddEffect("Attack", 33, 87).AddEffect("Precision", 33, 87),
                new AffixDefinition("AttPrec XII", AffixType.Prefix, 61).AddEffect("Attack", 36, 94).AddEffect("Precision", 36, 94),
            },
            new AffixDefinition[]
            {
                new AffixDefinition("AllStats 1", AffixType.Suffix, 5).AddEffect("Stats_All_Bonus", 1, 8),
                new AffixDefinition("AllStats 2", AffixType.Suffix, 13).AddEffect("Stats_All_Bonus", 9, 17),
                new AffixDefinition("AllStats 3", AffixType.Suffix, 20).AddEffect("Stats_All_Bonus", 18, 26),
                new AffixDefinition("AllStats 4", AffixType.Suffix, 27).AddEffect("Stats_All_Bonus", 27, 35),
                new AffixDefinition("AllStats 5", AffixType.Suffix, 34).AddEffect("Stats_All_Bonus", 36, 44),
                new AffixDefinition("AllStats 6", AffixType.Suffix, 41).AddEffect("Stats_All_Bonus", 45, 53),
                new AffixDefinition("AllStats 7", AffixType.Suffix, 49).AddEffect("Stats_All_Bonus", 54, 62),
                new AffixDefinition("AllStats 8", AffixType.Suffix, 56).AddEffect("Stats_All_Bonus", 63, 71),
            },
            new AffixDefinition[]
            {
                new AffixDefinition("Att 1", AffixType.Suffix, 1).AddEffect("Attack", 1, 8),
                new AffixDefinition("Att 2", AffixType.Suffix, 5).AddEffect("Attack", 9, 17),
                new AffixDefinition("Att 3", AffixType.Suffix, 9).AddEffect("Attack", 18, 26),
                new AffixDefinition("Att 4", AffixType.Suffix, 13).AddEffect("Attack", 27, 35),
                new AffixDefinition("Att 5", AffixType.Suffix, 17).AddEffect("Attack", 36, 44),
                new AffixDefinition("Att 6", AffixType.Suffix, 21).AddEffect("Attack", 45, 53),
                new AffixDefinition("Att 7", AffixType.Suffix, 25).AddEffect("Attack", 54, 62),
                new AffixDefinition("Att 8", AffixType.Suffix, 29).AddEffect("Attack", 63, 71),
                new AffixDefinition("Att 9", AffixType.Suffix, 33).AddEffect("Attack", 72, 80),
                new AffixDefinition("Att 10", AffixType.Suffix, 37).AddEffect("Attack", 81, 89),
                new AffixDefinition("Att 11", AffixType.Suffix, 41).AddEffect("Attack", 90, 98),
                new AffixDefinition("Att 12", AffixType.Suffix, 45).AddEffect("Attack", 99, 107),
                new AffixDefinition("Att 13", AffixType.Suffix, 49).AddEffect("Attack", 108, 116),
                new AffixDefinition("Att 14", AffixType.Suffix, 53).AddEffect("Attack", 117, 125),
                new AffixDefinition("Att 15", AffixType.Suffix, 57).AddEffect("Attack", 126, 134),
                new AffixDefinition("Att 16", AffixType.Suffix, 61).AddEffect("Attack", 135, 150),
            },
            new AffixDefinition[]
            {
                new AffixDefinition("Prec 1", AffixType.Suffix, 1).AddEffect("Precision", 1, 8),
                new AffixDefinition("Prec 2", AffixType.Suffix, 5).AddEffect("Precision", 9, 17),
                new AffixDefinition("Prec 3", AffixType.Suffix, 9).AddEffect("Precision", 18, 26),
                new AffixDefinition("Prec 4", AffixType.Suffix, 13).AddEffect("Precision", 27, 35),
                new AffixDefinition("Prec 5", AffixType.Suffix, 17).AddEffect("Precision", 36, 44),
                new AffixDefinition("Prec 6", AffixType.Suffix, 21).AddEffect("Precision", 45, 53),
                new AffixDefinition("Prec 7", AffixType.Suffix, 25).AddEffect("Precision", 54, 62),
                new AffixDefinition("Prec 8", AffixType.Suffix, 29).AddEffect("Precision", 63, 71),
                new AffixDefinition("Prec 9", AffixType.Suffix, 33).AddEffect("Precision", 72, 80),
                new AffixDefinition("Prec 10", AffixType.Suffix, 37).AddEffect("Precision", 81, 89),
                new AffixDefinition("Prec 11", AffixType.Suffix, 41).AddEffect("Precision", 90, 98),
                new AffixDefinition("Prec 12", AffixType.Suffix, 45).AddEffect("Precision", 99, 107),
                new AffixDefinition("Prec 13", AffixType.Suffix, 49).AddEffect("Precision", 108, 116),
                new AffixDefinition("Prec 14", AffixType.Suffix, 53).AddEffect("Precision", 117, 125),
                new AffixDefinition("Prec 15", AffixType.Suffix, 57).AddEffect("Precision", 126, 134),
                new AffixDefinition("Prec 16", AffixType.Suffix, 61).AddEffect("Precision", 135, 150),
            },
            new AffixDefinition[]
            {
                new AffixDefinition("Def 1", AffixType.Suffix, 1).AddEffect("Defense", 1, 8),
                new AffixDefinition("Def 2", AffixType.Suffix, 5).AddEffect("Defense", 9, 17),
                new AffixDefinition("Def 3", AffixType.Suffix, 9).AddEffect("Defense", 18, 26),
                new AffixDefinition("Def 4", AffixType.Suffix, 13).AddEffect("Defense", 27, 35),
                new AffixDefinition("Def 5", AffixType.Suffix, 17).AddEffect("Defense", 36, 44),
                new AffixDefinition("Def 6", AffixType.Suffix, 21).AddEffect("Defense", 45, 53),
                new AffixDefinition("Def 7", AffixType.Suffix, 25).AddEffect("Defense", 54, 62),
                new AffixDefinition("Def 8", AffixType.Suffix, 29).AddEffect("Defense", 63, 71),
                new AffixDefinition("Def 9", AffixType.Suffix, 33).AddEffect("Defense", 72, 80),
                new AffixDefinition("Def 10", AffixType.Suffix, 37).AddEffect("Defense", 81, 89),
                new AffixDefinition("Def 11", AffixType.Suffix, 41).AddEffect("Defense", 90, 98),
                new AffixDefinition("Def 12", AffixType.Suffix, 45).AddEffect("Defense", 99, 107),
                new AffixDefinition("Def 13", AffixType.Suffix, 49).AddEffect("Defense", 108, 116),
                new AffixDefinition("Def 14", AffixType.Suffix, 53).AddEffect("Defense", 117, 125),
                new AffixDefinition("Def 15", AffixType.Suffix, 57).AddEffect("Defense", 126, 134),
                new AffixDefinition("Def 16", AffixType.Suffix, 61).AddEffect("Defense", 135, 150),
            },
            new AffixDefinition[]
            {
                new AffixDefinition("Vit 1", AffixType.Suffix, 1).AddEffect("Vitality", 1, 8),
                new AffixDefinition("Vit 2", AffixType.Suffix, 5).AddEffect("Vitality", 9, 17),
                new AffixDefinition("Vit 3", AffixType.Suffix, 9).AddEffect("Vitality", 18, 26),
                new AffixDefinition("Vit 4", AffixType.Suffix, 13).AddEffect("Vitality", 27, 35),
                new AffixDefinition("Vit 5", AffixType.Suffix, 17).AddEffect("Vitality", 36, 44),
                new AffixDefinition("Vit 6", AffixType.Suffix, 21).AddEffect("Vitality", 45, 53),
                new AffixDefinition("Vit 7", AffixType.Suffix, 25).AddEffect("Vitality", 54, 62),
                new AffixDefinition("Vit 8", AffixType.Suffix, 29).AddEffect("Vitality", 63, 71),
                new AffixDefinition("Vit 9", AffixType.Suffix, 33).AddEffect("Vitality", 72, 80),
                new AffixDefinition("Vit 10", AffixType.Suffix, 37).AddEffect("Vitality", 81, 89),
                new AffixDefinition("Vit 11", AffixType.Suffix, 41).AddEffect("Vitality", 90, 98),
                new AffixDefinition("Vit 12", AffixType.Suffix, 45).AddEffect("Vitality", 99, 107),
                new AffixDefinition("Vit 13", AffixType.Suffix, 49).AddEffect("Vitality", 108, 116),
                new AffixDefinition("Vit 14", AffixType.Suffix, 53).AddEffect("Vitality", 117, 125),
                new AffixDefinition("Vit 15", AffixType.Suffix, 57).AddEffect("Vitality", 126, 134),
                new AffixDefinition("Vit 16", AffixType.Suffix, 61).AddEffect("Vitality", 135, 150),
            },
            new AffixDefinition[]
            {
                new AffixDefinition("Life 1", AffixType.Suffix, 1).AddEffect("Hitpoints_Max", 5, 10),
                new AffixDefinition("Life 2", AffixType.Suffix, 4).AddEffect("Hitpoints_Max", 11, 20),
                new AffixDefinition("Life 3", AffixType.Suffix, 8).AddEffect("Hitpoints_Max", 20, 34),
                new AffixDefinition("Life 4", AffixType.Suffix, 13).AddEffect("Hitpoints_Max", 35, 54),
                new AffixDefinition("Life 5", AffixType.Suffix, 17).AddEffect("Hitpoints_Max", 55, 79),
                new AffixDefinition("Life 6", AffixType.Suffix, 21).AddEffect("Hitpoints_Max", 80, 109),
                new AffixDefinition("Life 7", AffixType.Suffix, 25).AddEffect("Hitpoints_Max", 110, 139),
                new AffixDefinition("Life 8", AffixType.Suffix, 29).AddEffect("Hitpoints_Max", 140, 169),
                new AffixDefinition("Life 9", AffixType.Suffix, 34).AddEffect("Hitpoints_Max", 170, 199),
                new AffixDefinition("Life 10", AffixType.Suffix, 38).AddEffect("Hitpoints_Max", 200, 229),
                new AffixDefinition("Life 11", AffixType.Suffix, 42).AddEffect("Hitpoints_Max", 230, 259),
                new AffixDefinition("Life 12", AffixType.Suffix, 46).AddEffect("Hitpoints_Max", 260, 289),
                new AffixDefinition("Life 13", AffixType.Suffix, 50).AddEffect("Hitpoints_Max", 290, 319),
                new AffixDefinition("Life 14", AffixType.Suffix, 55).AddEffect("Hitpoints_Max", 320, 349),
                new AffixDefinition("Life 15", AffixType.Suffix, 59).AddEffect("Hitpoints_Max", 350, 400),
            },
            new AffixDefinition[]
            {
                new AffixDefinition("Cast 1", AffixType.Suffix, 1).AddEffect("Casting_Speed", 2f, 3f),
                new AffixDefinition("Cast 2", AffixType.Suffix, 6).AddEffect("Casting_Speed", 4f, 5f),
                new AffixDefinition("Cast 3", AffixType.Suffix, 12).AddEffect("Casting_Speed", 6f, 7f),
                new AffixDefinition("Cast 4", AffixType.Suffix, 18).AddEffect("Casting_Speed", 8f, 9f),
                new AffixDefinition("Cast 5", AffixType.Suffix, 24).AddEffect("Casting_Speed", 10f, 11f),
                new AffixDefinition("Cast 6", AffixType.Suffix, 30).AddEffect("Casting_Speed", 12f, 13f),
                new AffixDefinition("Cast 7", AffixType.Suffix, 36).AddEffect("Casting_Speed", 14f, 15f),
                new AffixDefinition("Cast 8", AffixType.Suffix, 42).AddEffect("Casting_Speed", 16f, 17f),
                new AffixDefinition("Cast 9", AffixType.Suffix, 48).AddEffect("Casting_Speed", 18f, 19f),
                new AffixDefinition("Cast 10", AffixType.Suffix, 54).AddEffect("Casting_Speed", 20f, 25f),
            },
            new AffixDefinition[]
            {
                new AffixDefinition("Thorns 1", AffixType.Suffix, 1).AddEffect("Thorns_Fixed", 1, 2),
                new AffixDefinition("Thorns 2", AffixType.Suffix, 4).AddEffect("Thorns_Fixed", 2, 4),
                new AffixDefinition("Thorns 3", AffixType.Suffix, 7).AddEffect("Thorns_Fixed", 4, 6),
                new AffixDefinition("Thorns 4", AffixType.Suffix, 11).AddEffect("Thorns_Fixed", 6, 8),
                new AffixDefinition("Thorns 5", AffixType.Suffix, 14).AddEffect("Thorns_Fixed", 8, 10),
                new AffixDefinition("Thorns 6", AffixType.Suffix, 18).AddEffect("Thorns_Fixed", 11, 13),
                new AffixDefinition("Thorns 7", AffixType.Suffix, 22).AddEffect("Thorns_Fixed", 14, 17),
                new AffixDefinition("Thorns 8", AffixType.Suffix, 26).AddEffect("Thorns_Fixed", 18, 22),
                new AffixDefinition("Thorns 9", AffixType.Suffix, 31).AddEffect("Thorns_Fixed", 24, 28),
                new AffixDefinition("Thorns 10", AffixType.Suffix, 35).AddEffect("Thorns_Fixed", 29, 32),
                new AffixDefinition("Thorns 11", AffixType.Suffix, 39).AddEffect("Thorns_Fixed", 33, 35),
                new AffixDefinition("Thorns 12", AffixType.Suffix, 43).AddEffect("Thorns_Fixed", 39, 42),
                new AffixDefinition("Thorns 13", AffixType.Suffix, 47).AddEffect("Thorns_Fixed", 45, 50),
                new AffixDefinition("Thorns 14", AffixType.Suffix, 52).AddEffect("Thorns_Fixed", 60, 66),
                new AffixDefinition("Thorns 15", AffixType.Suffix, 56).AddEffect("Thorns_Fixed", 70, 90),
            },
            new AffixDefinition[]
            {
                new AffixDefinition("DR 1", AffixType.Suffix, 4).AddEffect("Armor", 1, 4),
                new AffixDefinition("DR 2", AffixType.Suffix, 6).AddEffect("Armor", 5, 8),
                new AffixDefinition("DR 3", AffixType.Suffix, 9).AddEffect("Armor", 9, 12),
                new AffixDefinition("DR 4", AffixType.Suffix, 12).AddEffect("Armor", 13, 16),
                new AffixDefinition("DR 5", AffixType.Suffix, 15).AddEffect("Armor", 17, 20),
                new AffixDefinition("DR 6", AffixType.Suffix, 18).AddEffect("Armor", 21, 24),
                new AffixDefinition("DR 7", AffixType.Suffix, 21).AddEffect("Armor", 25, 28),
                new AffixDefinition("DR 8", AffixType.Suffix, 24).AddEffect("Armor", 29, 32),
                new AffixDefinition("DR 9", AffixType.Suffix, 27).AddEffect("Armor", 33, 36),
                new AffixDefinition("DR 10", AffixType.Suffix, 30).AddEffect("Armor", 37, 40),
                new AffixDefinition("DR 11", AffixType.Suffix, 33).AddEffect("Armor", 41, 44),
                new AffixDefinition("DR 12", AffixType.Suffix, 36).AddEffect("Armor", 45, 48),
                new AffixDefinition("DR 13", AffixType.Suffix, 39).AddEffect("Armor", 49, 52),
                new AffixDefinition("DR 14", AffixType.Suffix, 42).AddEffect("Armor", 53, 56),
                new AffixDefinition("DR 15", AffixType.Suffix, 45).AddEffect("Armor", 57, 60),
                new AffixDefinition("DR 16", AffixType.Suffix, 48).AddEffect("Armor", 61, 64),
                new AffixDefinition("DR 17", AffixType.Suffix, 51).AddEffect("Armor", 65, 68),
                new AffixDefinition("DR 18", AffixType.Suffix, 54).AddEffect("Armor", 69, 72),
                new AffixDefinition("DR 19", AffixType.Suffix, 57).AddEffect("Armor", 73, 76),
            },
            new AffixDefinition[]
            {
                new AffixDefinition("HealthGlobeBonus 1", AffixType.Suffix, 4).AddEffect("Health_Globe_Bonus_Health", 2, 3),
                new AffixDefinition("HealthGlobeBonus 2", AffixType.Suffix, 8).AddEffect("Health_Globe_Bonus_Health", 4, 5),
                new AffixDefinition("HealthGlobeBonus 3", AffixType.Suffix, 13).AddEffect("Health_Globe_Bonus_Health", 6, 7),
                new AffixDefinition("HealthGlobeBonus 4", AffixType.Suffix, 18).AddEffect("Health_Globe_Bonus_Health", 8, 9),
                new AffixDefinition("HealthGlobeBonus 5", AffixType.Suffix, 23).AddEffect("Health_Globe_Bonus_Health", 10, 11),
                new AffixDefinition("HealthGlobeBonus 6", AffixType.Suffix, 28).AddEffect("Health_Globe_Bonus_Health", 12, 13),
                new AffixDefinition("HealthGlobeBonus 7", AffixType.Suffix, 32).AddEffect("Health_Globe_Bonus_Health", 14, 15),
                new AffixDefinition("HealthGlobeBonus 8", AffixType.Suffix, 37).AddEffect("Health_Globe_Bonus_Health", 16, 17),
                new AffixDefinition("HealthGlobeBonus 9", AffixType.Suffix, 42).AddEffect("Health_Globe_Bonus_Health", 18, 19),
                new AffixDefinition("HealthGlobeBonus 10", AffixType.Suffix, 47).AddEffect("Health_Globe_Bonus_Health", 20, 21),
                new AffixDefinition("HealthGlobeBonus 11", AffixType.Suffix, 52).AddEffect("Health_Globe_Bonus_Health", 22, 23),
                new AffixDefinition("HealthGlobeBonus 12", AffixType.Suffix, 56).AddEffect("Health_Globe_Bonus_Health", 24, 25),
            },
            new AffixDefinition[]
            {
                new AffixDefinition("KillMana 1", AffixType.Suffix, 4).AddEffect("Resource_On_Kill", 1, 3),
                new AffixDefinition("KillMana 2", AffixType.Suffix, 9).AddEffect("Resource_On_Kill", 4, 6),
                new AffixDefinition("KillMana 3", AffixType.Suffix, 14).AddEffect("Resource_On_Kill", 7, 9),
                new AffixDefinition("KillMana 4", AffixType.Suffix, 19).AddEffect("Resource_On_Kill", 10, 12),
                new AffixDefinition("KillMana 5", AffixType.Suffix, 23).AddEffect("Resource_On_Kill", 13, 15),
                new AffixDefinition("KillMana 6", AffixType.Suffix, 28).AddEffect("Resource_On_Kill", 16, 18),
                new AffixDefinition("KillMana 7", AffixType.Suffix, 33).AddEffect("Resource_On_Kill", 19, 21),
                new AffixDefinition("KillMana 8", AffixType.Suffix, 38).AddEffect("Resource_On_Kill", 22, 24),
                new AffixDefinition("KillMana 9", AffixType.Suffix, 43).AddEffect("Resource_On_Kill", 25, 27),
                new AffixDefinition("KillMana 10", AffixType.Suffix, 47).AddEffect("Resource_On_Kill", 28, 30),
                new AffixDefinition("KillMana 11", AffixType.Suffix, 52).AddEffect("Resource_On_Kill", 31, 33),
                new AffixDefinition("KillMana 12", AffixType.Suffix, 57).AddEffect("Resource_On_Kill", 34, 36),
            },
            new AffixDefinition[]
            {
                new AffixDefinition("HitLife 1", AffixType.Suffix, 6).AddEffect("Hitpoints_On_Hit", 1),
                new AffixDefinition("HitLife 2", AffixType.Suffix, 11).AddEffect("Hitpoints_On_Hit", 2),
                new AffixDefinition("HitLife 3", AffixType.Suffix, 16).AddEffect("Hitpoints_On_Hit", 3),
                new AffixDefinition("HitLife 4", AffixType.Suffix, 20).AddEffect("Hitpoints_On_Hit", 4),
                new AffixDefinition("HitLife 5", AffixType.Suffix, 25).AddEffect("Hitpoints_On_Hit", 5),
                new AffixDefinition("HitLife 6", AffixType.Suffix, 30).AddEffect("Hitpoints_On_Hit", 6),
                new AffixDefinition("HitLife 7", AffixType.Suffix, 35).AddEffect("Hitpoints_On_Hit", 7),
                new AffixDefinition("HitLife 8", AffixType.Suffix, 40).AddEffect("Hitpoints_On_Hit", 8),
                new AffixDefinition("HitLife 9", AffixType.Suffix, 44).AddEffect("Hitpoints_On_Hit", 9),
                new AffixDefinition("HitLife 10", AffixType.Suffix, 49).AddEffect("Hitpoints_On_Hit", 10),
                new AffixDefinition("HitLife 11", AffixType.Suffix, 54).AddEffect("Hitpoints_On_Hit", 11),
                new AffixDefinition("HitLife 12", AffixType.Suffix, 59).AddEffect("Hitpoints_On_Hit", 12),
            },
            new AffixDefinition[]
            {
                new AffixDefinition("HitMana 1", AffixType.Suffix, 6).AddEffect("Resource_On_Hit", 1),
                new AffixDefinition("HitMana 2", AffixType.Suffix, 11).AddEffect("Resource_On_Hit", 2),
                new AffixDefinition("HitMana 3", AffixType.Suffix, 16).AddEffect("Resource_On_Hit", 3),
                new AffixDefinition("HitMana 4", AffixType.Suffix, 20).AddEffect("Resource_On_Hit", 4),
                new AffixDefinition("HitMana 5", AffixType.Suffix, 25).AddEffect("Resource_On_Hit", 5),
                new AffixDefinition("HitMana 6", AffixType.Suffix, 30).AddEffect("Resource_On_Hit", 6),
                new AffixDefinition("HitMana 7", AffixType.Suffix, 35).AddEffect("Resource_On_Hit", 7),
                new AffixDefinition("HitMana 8", AffixType.Suffix, 40).AddEffect("Resource_On_Hit", 8),
                new AffixDefinition("HitMana 9", AffixType.Suffix, 44).AddEffect("Resource_On_Hit", 9),
                new AffixDefinition("HitMana 10", AffixType.Suffix, 49).AddEffect("Resource_On_Hit", 10),
                new AffixDefinition("HitMana 11", AffixType.Suffix, 54).AddEffect("Resource_On_Hit", 11),
                new AffixDefinition("HitMana 12", AffixType.Suffix, 59).AddEffect("Resource_On_Hit", 12),
            },
        };
    }
}
